/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // SEMMAI brand tokens
        gold: {
          DEFAULT: '#D2AC47',
          dark: '#AE8625',
          light: '#EDC967',
          pale: '#F7EF8A',
        },
        brand: {
          red: '#7A1F2A',
          green: '#1E4B3A',
        },
        cream: '#FAF8F3',
        // Semantic tokens (used throughout existing components)
        primary: '#D2AC47',
        'primary-container': '#AE8625',
        'on-primary': '#1A1A1A',
        'on-primary-container': '#F7EF8A',
        'primary-fixed': '#EDC967',
        secondary: '#6B6B6B',
        'on-secondary': '#FAF8F3',
        'secondary-container': '#EDC967',
        'on-secondary-container': '#1A1A1A',
        tertiary: '#1E4B3A',
        'on-tertiary': '#FAF8F3',
        background: '#FAF8F3',
        'on-background': '#1A1A1A',
        surface: '#FAF8F3',
        'on-surface': '#1A1A1A',
        'surface-dim': '#E8E4D8',
        'surface-bright': '#FDFCF8',
        'surface-variant': '#F0ECE0',
        'on-surface-variant': '#6B6B6B',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F5F2EA',
        'surface-container': '#F0ECE0',
        'surface-container-high': '#EBE6D8',
        'surface-container-highest': '#E5DFCE',
        'inverse-surface': '#1A1A1A',
        'inverse-on-surface': '#FAF8F3',
        'inverse-primary': '#EDC967',
        outline: '#AE8625',
        'outline-variant': '#E5DEC9',
        error: '#7A1F2A',
        'on-error': '#ffffff',
        'error-container': '#F2DEE0',
        'on-error-container': '#7A1F2A',
        // accent: ONLY for sale prices, "Almost gone" badge text, low-stock warnings
        // Never use accent for buttons, links, or decorative elements
        accent: '#7A1F2A',
        'accent-muted': '#F2DEE0',
        muted: '#6B6B6B',
        divider: '#E5DEC9',
        faded: '#B5B0A4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        pill: '9999px',
      },
      maxWidth: {
        container: '1280px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        heading: ['"Playfair Display"', 'serif'],
        body: ['"Inter"', 'sans-serif'],
      },
      fontSize: {
        display: ['clamp(42px, 6vw, 68px)', { lineHeight: '1', letterSpacing: '-0.01em' }],
        'headline-lg': ['clamp(26px, 4vw, 40px)', { lineHeight: '1.1' }],
        'label-sm': ['10px', { lineHeight: '1', letterSpacing: '2.5px' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
