/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#16392B',
        'primary-container': '#1e4e38',
        'on-primary': '#F5F5EC',
        'on-primary-container': '#c4dfcf',
        'primary-fixed': '#a8d4bc',
        secondary: '#3d6b55',
        'on-secondary': '#F5F5EC',
        'secondary-container': '#c8e6d4',
        'on-secondary-container': '#16392B',
        tertiary: '#5a7d6a',
        'on-tertiary': '#F5F5EC',
        background: '#F5F5EC',
        'on-background': '#16392B',
        surface: '#F5F5EC',
        'on-surface': '#16392B',
        'surface-dim': '#ddddd4',
        'surface-bright': '#FAFAF5',
        'surface-variant': '#d5e6dc',
        'on-surface-variant': '#3d5f4e',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F0F0E8',
        'surface-container': '#EAEADF',
        'surface-container-high': '#E4E4D8',
        'surface-container-highest': '#DEDED1',
        'inverse-surface': '#16392B',
        'inverse-on-surface': '#F5F5EC',
        'inverse-primary': '#a8d4bc',
        outline: '#4a7560',
        'outline-variant': '#b0c8bb',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        // accent: ONLY for sale prices, "Almost gone" badge text, low-stock warnings
        // Never use accent for buttons, links, or decorative elements
        accent: '#8B6914',
        'accent-muted': '#F5EDD6',
        muted: '#7a7a6e',
        divider: '#E4E3D8',
        faded: '#aaa8a0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        pill: '9999px',
      },
      maxWidth: {
        container: '1280px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['clamp(42px, 6vw, 68px)', { lineHeight: '1', letterSpacing: '-0.01em' }],
        'headline-lg': ['clamp(26px, 4vw, 40px)', { lineHeight: '1.1' }],
        'label-sm': ['10px', { lineHeight: '1', letterSpacing: '2.5px' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
